package com.example.gariache;

public class User {
    private String id;      // though Firebase uses String IDs
    private String studentId;
    private String name;
    private String email;
    private String phone;
    private String password;

    // No-argument constructor for Firebase
    public User() {}

    public User(String id, String studentId, String name, String email, String phone, String password) {
        this.id = id;
        this.studentId = studentId;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.password = password;
    }

    // Getters and setters (autogenerated in Android Studio)
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getStudentId() { return studentId; }
    public void setStudentId(String studentId) { this.studentId = studentId; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getPhone() { return phone; }
    public void setPhone(String phone) { this.phone = phone; }

    public String getPassword() { return password; }
    public void setPassword(String password) { this.password = password; }
}
